CONFIG = {
    "aim_enabled": False,
    "mock_hid": True,
    "confidence": 0.45,
    "nms": 0.50,
    "target_size": 416,
    "detect_period_ms": 240,
    "fov_radius_ratio": 0.28,
    "roi_padding": 1.18,
    "dashboard_period_ms": 200,
    "aim_part": "head",
    "aim_head_ratio": 0.20,
    "aim_chest_ratio": 0.42,
    "strength": 0.72,
    "smoothing": 0.58,
    "sensitivity_x": 0.42,
    "sensitivity_y": 0.42,
    "max_step_px": 110,
    "deadzone_px": 7,
    "swipe_ms": 45,
    "look_anchor_x": 0.78,
    "look_anchor_y": 0.50,
    "self_filter": True,
    "self_exclusion": [0.36, 0.58, 0.64, 1.00],
    "target_tags": ["enemy"],
    "model_param": "raven.param",
    "model_bin": "raven.bin",
    "model_yaml": "data.yaml",
}
